#!/bin/bash
sudo yum -y install wget
cd /home/ec2-user
wget  https://aws-codedeploy-us-east-1.s3.amazonaws.com/latest/codedeploy-agent.msi
sudo chmod +x ./install
sudo ./install auto
sudo yum install -y python-pip
sudo pip install awscli
